/**
 * This class extends JFrame to generate a GUI.
 * This GUI provides 3 buttons:
 * <UL>
 * <LI/> Choose file
 * <LI/> Start
 * <LI/> Finish
 * </UL>
 * These 3 buttons can achieve all operations in this GUI. After clicking "Start" button, the program will automatically
 * parse and report error warnings. After clicking "Finish" button, the window will disappear.
 * @author Miao Cai
 * @since 15/12/2019 9:32 PM
 */
package Interface;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Paths;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

import Scanner.Recognizer;


public class FileHelper extends javax.swing.JFrame  {

    private final JFileChooser openFileChooser;
    private BufferedReader br;
    /**
     * Creates new form FileHelper
     */
    public FileHelper() {
        initComponents();
        openFileChooser = new JFileChooser();
        File file = new File("test/test1.txt");
        openFileChooser.setCurrentDirectory(file);
        openFileChooser.setFileFilter(new FileNameExtensionFilter("TEXT FILES","txt","text"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        openBtn = new javax.swing.JButton();
        fileName = new javax.swing.JLabel();
        tArea = new JTextArea();
        tArea.setLineWrap(true);
        tArea.setEditable(false);
        scrollPane1 = new javax.swing.JScrollPane(tArea);
        finishBtn = new javax.swing.JButton();
        startBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lexical Parser");
        setBackground(new java.awt.Color(245, 245, 245));
        setResizable(false);

        openBtn.setBackground(new java.awt.Color(255, 255, 255));
        openBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        openBtn.setText("Choose File");
        openBtn.setToolTipText("");
        openBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBtnActionPerformed(evt);
            }
        });

        fileName.setBackground(new java.awt.Color(245, 245, 245));
        fileName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        fileName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fileName.setText("No file chosen");

        scrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        finishBtn.setBackground(new java.awt.Color(255, 255, 255));
        finishBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        finishBtn.setText("Finish");
        finishBtn.setEnabled(false);
        finishBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                finishBtnMouseClicked(evt);
            }
        });

        startBtn.setBackground(new java.awt.Color(255, 255, 255));
        startBtn.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        startBtn.setText("Start");
        startBtn.setEnabled(false);
        startBtn.setToolTipText("");
        startBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(startBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(finishBtn))
                    .addComponent(scrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(openBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fileName, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openBtn)
                    .addComponent(fileName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finishBtn)
                    .addComponent(startBtn))
                .addContainerGap())
        );

        pack();
    }

    private void openBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openBtnActionPerformed
        int returnValue = openFileChooser.showOpenDialog(this);
        
        if (returnValue == JFileChooser.APPROVE_OPTION){
            try {
                br = new BufferedReader(new FileReader(openFileChooser.getSelectedFile()));
                fileName.setText(openFileChooser.getSelectedFile().getName());
                startBtn.setEnabled(true);
            } catch(IOException e){
                fileName.setText("IO error! Try again later.");
            }
        } else {
            fileName.setText("No file chosen");
        }
    }

    /**
     * This method is used to listen the event from "finish" button.
     * @param evt Mouse event
     */
    private void finishBtnMouseClicked(java.awt.event.MouseEvent evt) {
        System.exit(0);
    }

    /**
     * This method is used to listen the event from "Start" button.
     * @param evt Mouse event
     */
    private void startBtnMouseClicked(java.awt.event.MouseEvent evt) {
        /* If "Start" button is enable, we can start parsing.
         * Otherwise, wait until the previous process ends.
         */
        if (startBtn.isEnabled()){
            startBtn.setEnabled(false);
            openBtn.setEnabled(false);
            // Clear the text area.
            tArea.setText("");
            Recognizer recognizer = new Recognizer(br, tArea, finishBtn, openBtn);
        }

    }

    /**
     * This main function is used to execute the GUI driver.
     * @param args The command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FileHelper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FileHelper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FileHelper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileHelper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FileHelper().setVisible(true);
            }
        });
    }

    // Variables declaration
    private JLabel fileName;
    private JButton finishBtn;
    private JButton startBtn;
    private JButton openBtn;
    private JTextArea tArea;
    private JScrollPane scrollPane1;
    // End of variables declaration
}
